### ISSUE TITLE
UTF-8 decoding issue on macOS and Linux

### ISSUE THREAD

**Issue by leonmoonen** [dlesbre/bibtex-autocomplete#8]
Hi,

I'm trying to autocomplete the DOIs in a bib file and get a crash both on macOS (Ventura 13.2.1 / Python 3.10.2) and Linux (Ubuntu 20.04.5 LTS / Python 3.8.10). On both systems `btac` is pip-installed in it's own venv and crashes with (minor path variations on) the following error:

```
Querying databases: |██████████████████████████████████████⚠︎ | (!) [95%] in 35:47.3
Traceback (most recent call last):
  File "/home/leon/src/bibtex-autocomplete/venv/bin/btac", line 8, in <module>
    sys.exit(main())
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/core/main.py", line 106, in main
    completer.autocomplete(args.verbose < 0)
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/core/autocomplete.py", line 170, in autocomplete
    self.update_entry(entries[position], threads, position)
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/core/autocomplete.py", line 193, in update_entry
    to_add = self.sanitize(to_add)
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/core/autocomplete.py", line 235, in sanitize
    if doi_checker.query() is not True:
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/lookups/condition_mixin.py", line 27, in query
    return super().query()
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/lookups/abstract_base.py", line 119, in query
    return self.process_data(data)
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/APIs/doi.py", line 92, in process_data
    if self.check_url(value["data"]["value"].to_str()):
  File "/home/leon/src/bibtex-autocomplete/venv/lib/python3.8/site-packages/bibtexautocomplete/APIs/doi.py", line 101, in check_url
    text = normalize_str_weak(final.data.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 10: invalid start byte
```

The bibfile has 580 entries; it seems they all get queried before the crash... Does the above give any indication that could help to drill down to the offending entry?

cheers,
Leon

**Comment by dlesbre** [comment]
Hi, thanks for reporting this. 

Its a bug resulting of my overzealous testing. I've pushed a new version (1.1.7) that should solve the issue.

What happens is that when `btac` finds a DOI from one of the databases, it checks that this DOI resolves to something by querying https://dx.doi.org/xxxx/yyyy.zzzzz. The problem is that sometimes this resolve to a valid website and not a 404 for absent DOIs (namely https://link.springer.com/deleted). So I added some code to read the HTML page returned and check for these "not found" pages. Of course this only works if the returned data is a plaintext file, and not say, a binary PDF...

For reference, if you want to narrow the problem to an offending entry, try using verbose mode (`-v` argument). It prints entries' IDs as it completes them so the first entry that isn't printed is likely to be the one that caused a crash.

**Comment by leonmoonen** [comment]
Hi, 

Thanks for the quick solution. I'm unfortunately still getting a bug, now about a space in a URL; based on your description this is likely in the same part of the testing code: 

```
http.client.InvalidURL: URL can't contain control characters. '/content/pdf/bfm:978-1-4615-4625-2/1?pdf=chapter toc&error=cookies_not_supported&code=9a0c37ce-8f6a-4962-aef1-84ccc085b1bf' (found at least ' ')
```

The narrowing hint worked very well, the following entry causes this error:
```
@book{wohlin2012experimentation,
  title = {Experimentation in Software Engineering},
  author = {Wohlin, Claes and Runeson, Per and H{\"o}st, Martin and Ohlsson, Magnus C and Regnell, Bj{\"o}rn and Wessl{\'e}n, Anders},
  year = {2012},
  publisher = {{Springer Science \& Business Media}}
}
```

cheers,
Leon

**Comment by dlesbre** [comment]
I see the problem, thanks for providing the entry.

I've pushed a new version (1.1.8) with better URL normalization to avoid this issue.

I've also added code so that these errors in resolving a single URL/DOI/query don't crash the whole application.
